# Generated by Django 5.1.4 on 2024-12-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0002_alter_foodcollection_options_alter_fooditem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditem.fooditem')),
            ],
        ),
    ]
