# Generated by Django 5.1.4 on 2025-01-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='img',
            field=models.CharField(default='https://live.staticflickr.com/65535/53617693698_9a55f62c16_o.png', max_length=255),
            preserve_default=False,
        ),
    ]
