# Generated by Django 5.1.4 on 2025-02-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0004_fooditem_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditem.fooditem')),
            ],
        ),
    ]
