# Generated by Django 5.1.4 on 2025-03-24 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
